### ISSUE TITLE
B2-7 ASUS Mini PC (R-B) COM6 skips logs at irregular intervals

### ISSUE THREAD

**Issue by sormazabal** [JihwanMyung/LocoBox#1]
In a 1-hr interval (from 14:00 - 15:00)  COM6 (connected to the ASUS Mini PC ) skipped the following intervals: 14:03/14:13/14:21/14:29/14:37/14:45/14:53/15:01 .
COM6 remained working stable during the same interval, even both are connected to the same computer.
Image for reference:
![image](https://user-images.githubusercontent.com/7980453/178445376-a01589bd-ccd4-4482-ae2c-4f854a5ba3a6.png)
(Reported by Dino)

**Comment by JihwanMyung** [comment]
Resolved. Data saves at regular interval based on RTC and not the delay() integration.
